### ISSUE TITLE
Experience not matching level.

### ISSUE THREAD

**Issue by Xeddicus** [pclifford/borderlands2#3]
After setting a level on a character the experience isn't changed, so you have the experience of level 1 at whatever level you set. This may be an intentional omission, but in case not here it is.

**Comment by pclifford** [comment]
It was semi-intentional.  I don't use the modified characters for anything serious so it didn't seem worth adjusting the experience value, but I've added the necessary code now.  If the character's experience doesn't match the approximate upper and lower bounds for their new level it'll be reset to roughly what it would have been if they'd just levelled up.

**Comment by Xeddicus** [comment]
Thanks for the update (also for removing the LZO bindings, I had a bit of a hassle getting that set up then you removed the requirement an hour later, but thanks:P).
