### ISSUE TITLE
I feel retarded! :( need help

### ISSUE THREAD

**Issue by 70P4537Y** [pclifford/borderlands2#4]
I'm following the instructions but i always get "SyntaxError: invalid syntax"
I know I'm doing something wrong but i can't figure it out :/

thanks for your hard work btw! :)

**Comment by pclifford** [comment]
My guess would be that you downloaded the web page displaying the savefile.py file contents (https://github.com/pclifford/borderlands2/blob/master/savefile.py) rather than the file itself.  You can download all the files together in a zip archive by clicking on the "ZIP" button near the top on the main page, or one individually by clicking on the "Raw" button on that file's page.

**Comment by 70P4537Y** [comment]
Hey thanks for the quick response!
well, yeah i did click on the ZIP button and downloaded it, then i extracted it, but i guess i'm doing something wrong...
Where do i need to extract the filesave.py file?

**Comment by Xeddicus** [comment]
You can extract the savefile.py file anywhere assuming python is set up properly (in your PATH).

**Comment by pclifford** [comment]
If you're still stuck try grabbing the latest version and see if the WINDOWS-HOWTO.txt file helps.

**Comment by 70P4537Y** [comment]
you know what guys? i got it! :P THANKS A LOT PCLIFFORD for the script! you're awesome!
